### ISSUE TITLE
Les scores affichés dans la gui semblent faux.

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#1]
> ###### Originally posted 2015-04-26 22:02 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

L'api me dit ça :
Tour : 99, mon score : 274745, autre score : 42446

le code est le suivant :
Printf.printf "Tour : %d, mon score : %d, autre score : %d\n%!"
    (tour_actuel ())
    (score (moi ()))
    (score (adversaire ()));

alors que la gui me dit qu'on en est à : 931 vs 3681

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-27 14:39 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Pourrais-tu me fournir ton dump json pour examiner la partie ?

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-27 20:36 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Ça devrait être corrigé maintenant.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-28 02:21 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Ah, tiens, il existe un bouton "Résoudre" sur Bitbucket !
