### ISSUE TITLE
utiliser les fonctions d'historique dans la gui ?

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#10]
> ###### Originally posted 2015-05-01 14:16 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

ça pourrait être sympa que la gui mémorise les dernieres positions du gars pour afficher une fleche.

On pourrait aussi afficher des cercles autour des derniers portails capturés.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 17:51 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Je plussoie. PM, encore du boulot pour quand tu reviens !

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/jeux/2015/-/issues/10
