### ISSUE TITLE
ajouter des coordonnées sur la gui

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#2]
> ###### Originally posted 2015-04-28 06:52 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

ajouter des coordonnées sur la gui pourrait permettre de tester les champions des candidats plus facilement.

**Comment by pmderodat** [comment]
> ###### Originally posted 2015-04-29 06:59 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Will do ASAP: next thing on my plate. ;-)

**Comment by pmderodat** [comment]
> ###### Originally posted 2015-04-29 19:55 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

GUI: display cell coordinates on map click

Fixes #2


→ <<cset fb5b565f5eae>>
