### ISSUE TITLE
ajouter une fonction dans_triangle

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#3]
> ###### Originally posted 2015-04-28 20:26 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

ça pourrait être sympa d'avoir une fonction qui nous dit si un point est dans un triangle.
Cette fonction prendrait 4 positions et renverrait true si le premier parametre est dans le triangle formé par les 3 suivants.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-28 21:12 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

En effet, la fonction est déjà implémentée dans geometry.cc, c'est une omission majeure de la section "algorithmes offerts gratuitement".

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-28 21:31 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Résolu en même temps que l'issue #4.
