### ISSUE TITLE
Pas de fonction pour connaître son nombre de points de deplacements/actions restants.

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#4]
> ###### Originally posted 2015-04-28 20:38 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

Ne pas avoir ces deux fonctions n'est pas forcément un gros problème, mais ça permettrait au gars de faire un "assert j'ai bien compté" ou autre.

A mon avis, c'est pas très dur à ajouter, dont autant les mettre.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-28 21:31 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

C'est bon, c'est fait.
