### ISSUE TITLE
hist_portails_neutralises et liste_liens plantent

### ISSUE THREAD

**Issue by coucou747** [prologin/prologin2015#5]
> ###### Originally posted 2015-04-29 21:09 by [coucou747](https://bitbucket.org/coucou747/) on Bitbucket

Les fonctions : hist_portails_neutralises et liste_liens
plantent le client.

(clients écrits en ocaml)

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-04-29 21:53 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Les fonctions hist_* n'ont pas encore été implémentées, c'est normal.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 03:15 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Les fonctions hist_* ont été implémentées et ne devraient plus provoquer de plantage, donc je marque résolu. Mais il n'est pas garanti à cet instant qu'elles soient correctes…

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 03:16 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Ah, et ton fix pour liste_liens était correct.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 13:36 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Merci pour le fix de l'allocation initiale de history_info. J'ai aussi poussé d'autres fixes de type "erreur de logique".
