### ISSUE TITLE
Fermeture immédiate de la GUI

### ISSUE THREAD

**Issue by nguyentito** [prologin/prologin2015#7]
> ###### Originally posted 2015-05-01 00:32 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

La GUI en mode spectateur refuse de laisser se fermer sa fenêtre, préférant afficher un message "attente de la fin de la partie". N'est-il vraiment pas possible de faire quitter prématurément un spectateur avec stechec2 ?

Aussi, il faudrait expliciter dans le message d'erreur "tour précédent non disponible" que ça ne marche qu'en mode replay.

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 00:38 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Je viens de voir que c'est précisé dans l'aide pour le tour précédent, mais je fais pas forcément confiance aux gens pour faire attention au texte dans l'aide.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/jeux/2015/-/issues/7
