### ISSUE TITLE
Comment quitter la GUI (en particulier en plein écran) ?

### ISSUE THREAD

**Issue by nguyentito** [prologin/prologin2015#8]
> ###### Originally posted 2015-05-01 00:46 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

A priori la solution canonique pour quitter la GUI sans accès à un bouton "close" est d'appuyer sur Q. Cependant il n'est précisé nulle part que Q permet de faire ça. Il faut le rajouter à l'aide.

De plus Q ne marche pas lorsque la popup d'aide est ouverte, ça peut être perturbant pour qqn qui va ouvrir l'aide, voit que Q sert à fermer, teste et voir que ça ne fonctionne pas.

Dernier point (détail mineur) : sous XMonad, Win+Shift+C n'arrive pas à fermer la fenêtre lorsqu'elle est en plein écran. Vu que l'environnement des candidats sera pas un tiling WM avec plein de raccourcis clavier, on s'en fiche un peu.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/jeux/2015/-/issues/8
