### ISSUE TITLE
Quelques suggestions pour améliorer la sidebar dans la GUI

### ISSUE THREAD

**Issue by nguyentito** [prologin/prologin2015#9]
> ###### Originally posted 2015-05-01 01:07 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

(priority=minor parce que c'est pas tellement important)

- Le message "attente du prochain champion" n'a pas de sens en mode replay, ça serait bien de le virer
- Quitte à différencier les messages en fonction du mode où on se trouve, il serait bon d'indiquer "Mode replay" ou "Mode spectateur" sur la GUI vu que ça a des répercussions sur les fonctionnalités disponibles
- En plus d'indiquer les coordonnées du point sélectionné, ne peut-on pas afficher s'il s'agit d'un portail, et si oui, le possesseur du portail et le nombre de liens et de champs incidents ?
- Ce serait plus clair qu'on peut cliquer sur la map avec un curseur/réticule
- Au lieu d'avoir un toute petite zone en haut indiquant le score actuel des deux joueurs, on peut pour chacun afficher des stats : score mais aussi nombre de portails, liens et triangles contrôlés + score par tour rapporté par l'aire actuellement contrôlée. (Et faire du stacking vertical au lieu d'horizontal pour avoir la place.)
- On pourrait grossir pas mal la police pour améliorer la lisibilité (et écrire juste "H : aide" au lieu de "H : afficher/cacher l'aide")

En résumé : il reste plein de place sur la sidebar, pourquoi ne pas la remplir ?

S'il y a besoin de modifier le dumper pour rajouter des informations supplémentaires dans le JSON généré, je peux m'en charger.

**Comment by pmderodat** [comment]
> ###### Originally posted 2015-05-01 07:19 by [pmderodat](https://bitbucket.org/pmderodat/) on Bitbucket

Bonnes remarques, mais pourquoi celles-ci n’arrivent que maintenant ? On est à moins d’une semaine de la finale et je pars en week-end prolongé (= sans station de travail raisonnable)… Je ne sais pas si je vais avoir le temps de me pencher là-dessus assez tôt…

Si j’ai bien compris toutes les informations sont déjà présentes dans le dump : portails, propriétaires, boucliers, liens et triangles. Compléter le dumper n’est de toute manière pas la partie difficile. ;-)

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-01 12:04 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Ben, avant ça, il y avait des trucs plus urgents à faire genre le mode spectateur. Si t'as pas le temps je tenterai d'introduire ces modifs de façon plus ou moins moche en recopiant du code de 2013…

**Comment by nguyentito** [comment]
> ###### Originally posted 2015-05-11 14:30 by [nguyentito](https://bitbucket.org/nguyentito/) on Bitbucket

Certaines de ces suggestions ont été implémentées, et la finale est passée.
